### ISSUE TITLE
PIP can't install correct versions

### ISSUE THREAD

**Issue by carlososuna86** [ZT2wo/OcrWarframe#1]
I downloaded this repo, and tried to install the dependencies.

I tried to use this basic **Requirements.txt** file:
```
easyocr
numpy
image_slicer
pandas
Pillow
PIL
```

And got this error:
```
python -m pip install -r Requirements.txt
Collecting easyocr
  Using cached easyocr-1.4.1-py3-none-any.whl (63.6 MB)
Collecting numpy
  Using cached numpy-1.22.3-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting image_slicer
  Using cached image_slicer-2.1.1-py2.py3-none-any.whl (8.3 kB)
Collecting Pillow
  Using cached Pillow-9.0.1-cp39-cp39-win_amd64.whl (3.2 MB)
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

```

**Comment by carlososuna86** [comment]
From what I read, if you have functioning versions of those libraries installed, the easiest way to find the correct versions would be to run:
`pip freeze > Requirements.txt`

And then upload the file to this repository.

**Comment by ZT2wo** [comment]
> From what I read, if you have functioning versions of those libraries installed, the easiest way to find the correct versions would be to run: `pip freeze > Requirements.txt`
> 
> And then upload the file to this repository.

This is correct, however this is not an issue with my code. "PIL" is just the import for pillow. not something that you have to pip.
